version: "2"
services:

  redis:
    build: build
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000
    environment:
      - XXX_DIR=/tmp
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/redis_data
      - redislog:/redis_log

volumes:
  redisdata:
    driver: local
  redislog:
    driver: local
